name: pangea_sdk
description: Flutter package for Pangea, enabling using Pangea services
version: 0.0.1-beta.1
homepage: https://pangea.cloud/
repository: https://github.com/pangeacyber/pangea_flutter

false_secrets:
  - example/**

environment:
  sdk: ">=3.5.3 <4.0.0"
  flutter: ">=3.24.3"

dependencies:
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.3
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
