name: pangea_sdk
description: Flutter package for Pangea, enabling using Pangea services
version: 0.0.1-beta.1
homepage: https://pangea.cloud/
repository: https://github.com/pangeacyber/pangea_flutter

false_secrets:
  - example/**

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  http: ^1.2.1
  flutter_inappwebview: ^6.0.0-beta.24+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
